In [6]:
import numpy as np
import random

X = np.array([random.random() for _ in range(10)])

In [7]:
X

array([ 0.28349119,  0.62899842,  0.10364287,  0.69182772,  0.29870621,
        0.7443963 ,  0.7233856 ,  0.39989601,  0.36442191,  0.40194952])

In [8]:
limit = 10/4.0

In [11]:
y = np.array([0 if x<limit else 1 for x in np.cumsum(X)])
y

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [18]:
def get_seq(n_timesteps):
    X = np.array([random.random() for _ in range(n_timesteps)])
    limit = n_timesteps/4.0
    y = np.array([0 if x<limit else 1 for x in np.cumsum(X)])
    X = X.reshape(1,n_timesteps,1)
    y = y.reshape(1,n_timesteps,1)
    return X,y

In [19]:
X, y = get_seq(10)
print(X)
print(y)

[[[ 0.23840832]
  [ 0.69843951]
  [ 0.84380894]
  [ 0.3015121 ]
  [ 0.80727075]
  [ 0.54907156]
  [ 0.02949273]
  [ 0.43002843]
  [ 0.44112304]
  [ 0.97847243]]]
[[[0]
  [0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]]]


In [28]:
from keras.models import Sequential
from keras.layers import Dense,LSTM,TimeDistributed,Bidirectional

model = Sequential()
model.add(Bidirectional(LSTM(20, return_sequences=True), input_shape=(n_timesteps, 1)))
model.add(TimeDistributed(Dense(1,activation = 'sigmoid')))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['acc'])

In [29]:
# train LSTM
for epoch in range(1000):
    # generate new random sequence
    X,y = get_seq(n_timesteps)
    # fit model for one epoch on this sequence
    model.fit(X, y, epochs=1, batch_size=1, verbose=2)

Epoch 1/1
 - 1s - loss: 0.6976 - acc: 0.2000
Epoch 1/1
 - 0s - loss: 0.6897 - acc: 0.7000
Epoch 1/1
 - 0s - loss: 0.6892 - acc: 0.8000
Epoch 1/1
 - 0s - loss: 0.6879 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.6835 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.6850 - acc: 0.8000
Epoch 1/1
 - 0s - loss: 0.6805 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6848 - acc: 0.7000
Epoch 1/1
 - 0s - loss: 0.6865 - acc: 0.6000
Epoch 1/1
 - 0s - loss: 0.6798 - acc: 0.8000
Epoch 1/1
 - 0s - loss: 0.6801 - acc: 0.8000
Epoch 1/1
 - 0s - loss: 0.6835 - acc: 0.7000
Epoch 1/1
 - 0s - loss: 0.6801 - acc: 0.7000
Epoch 1/1
 - 0s - loss: 0.6763 - acc: 0.8000
Epoch 1/1
 - 0s - loss: 0.6607 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6585 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.6735 - acc: 0.7000
Epoch 1/1
 - 0s - loss: 0.6663 - acc: 0.8000
Epoch 1/1
 - 0s - loss: 0.6648 - acc: 0.8000
Epoch 1/1
 - 0s - loss: 0.6562 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.6643 - acc: 0.7000
Epoch 1/1
 - 0s - loss: 0.6728 - acc: 0.7000
Epoch 1/1


 - 0s - loss: 0.2605 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.2353 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.1954 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.1534 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.4182 - acc: 0.8000
Epoch 1/1
 - 0s - loss: 0.1091 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0982 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2153 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.0973 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1527 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.3055 - acc: 0.8000
Epoch 1/1
 - 0s - loss: 0.2015 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.1851 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.1762 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.1022 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0948 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0956 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1690 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.2605 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.1217 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.1020 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0950 - acc: 1.0000
Epoch 1/1
 - 0s - lo

Epoch 1/1
 - 0s - loss: 0.1116 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1865 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.1175 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.1024 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1433 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.1190 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1501 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.2027 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.1117 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1001 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1181 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1657 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.1088 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4071 - acc: 0.8000
Epoch 1/1
 - 0s - loss: 0.1207 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.0960 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1099 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1515 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.3084 - acc: 0.8000
Epoch 1/1
 - 0s - loss: 0.1583 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.1047 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.9546 - acc: 0.4000
Epoch 1/1


 - 0s - loss: 0.1154 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.1434 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.1318 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.0997 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1001 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.1034 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1431 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.1465 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.1278 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.0831 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1586 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.0648 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0737 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0801 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0743 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2671 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.1038 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.2340 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.1435 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.0928 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0807 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0842 - acc: 1.0000
Epoch 1/1
 - 0s - lo

Epoch 1/1
 - 0s - loss: 0.1206 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1051 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0880 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0939 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0870 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1752 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.1154 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0830 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0842 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1818 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.0902 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1194 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.2470 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.0935 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0925 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1301 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.1095 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2880 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.0831 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1708 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.0925 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4227 - acc: 0.7000
Epoch 1/1


 - 0s - loss: 0.0526 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1267 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0610 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1082 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.2253 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.0784 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0977 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0883 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0560 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0804 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3020 - acc: 0.8000
Epoch 1/1
 - 0s - loss: 0.1511 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.1518 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.2597 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0822 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2872 - acc: 0.8000
Epoch 1/1
 - 0s - loss: 0.0678 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1129 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.0795 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1721 - acc: 0.9000
Epoch 1/1
 - 0s - loss: 0.0807 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0719 - acc: 1.0000
Epoch 1/1
 - 0s - lo

In [32]:
X,y = get_seq(n_timesteps)
yhat = model.predict_classes(X, verbose=0)
for i in range(n_timesteps):
    print('Expected:', y[0, i], 'Predicted', yhat[0, i])

Expected: [0] Predicted [0]
Expected: [0] Predicted [0]
Expected: [0] Predicted [0]
Expected: [0] Predicted [0]
Expected: [0] Predicted [0]
Expected: [0] Predicted [0]
Expected: [1] Predicted [1]
Expected: [1] Predicted [1]
Expected: [1] Predicted [1]
Expected: [1] Predicted [1]
